### ISSUE TITLE
Build and locate XCUITest Suite for device

### ISSUE THREAD

**Issue by emin-grbo** [sersoft-gmbh/xcodebuild-action#149]
Hi!
Trying to build and ZIP the XCUI test suite, but no matter which approach I take, I have issues retrieving the file.

I was only ever able to get the file usually located in `DerivedData/**/Build/Products/Debug-iphonesimulator/`
never the one which I actually need `DerivedData/**/Build/Products/Debug-iphoneos/`

In other words, my build target needs to be for generic/device. 

Is there a setting I am missing where a runner would be built for a device?
Thank you!

```
## BUILD AND SAVE XCTEST RUNNER ====================================================
    - name: Build XCUITest via action
      uses: sersoft-gmbh/xcodebuild-action@v2.0.1
      with:
       workspace: TARGET.xcworkspace
       scheme: TARGET-UITests
       destination: generic/platform=iOS
       action: build-for-testing
       cloned-source-packages-path: "SourcePackages"
       allow-provisioning-updates: true

    - name: Save XCUI
      uses: actions/upload-artifact@v3
      with:
        name: TARGET-UITests-Runner.app
        path: TARGET-UITests-Runner.app
        
    - name: Zip Runner
      uses: vimtor/action-zip@v1
      with:
        files: TARGET-UITests-Runner.app
        dest: TARGET-UITests-Runner.zip
```
