### ISSUE TITLE
xcodebuild: error: '[app_name].xcworkspace' does not exist.

### ISSUE THREAD

**Issue by kbrady1** [sersoft-gmbh/xcodebuild-action#2]
I've set up a simple workflow, and have played around with a couple different path settings, but I get this same error every single time.
`xcodebuild: error: '[app_name].xcworkspace' does not exist.`
```yaml
name: TestAction

on:
  push:
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Xcodebuild Action
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      with:
        # The path to the xcworkspace to build. Mutually exclusive with `project`.
        project: [app_name].xcworkspace
        # The scheme to build. Required when using a workspace.
        scheme: [scheme]
```
File structure from root of repository: 
.github.com/workflows/testAction.yml
[app_name]/[app_name].xcworkspace

**Comment by ffried** [comment]
@kbrady1 You need to specify the path from the root of the repository to the project or (in your case) workspace. In your example, `xcodebuild` would search the workspace at `/[app name].xcworkspace` in the root of the repository. According to your file structure, the workspace is nested inside a folder, though.

Please give the following setup a try:

```yaml
name: TestAction

on:
  push:
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Xcodebuild Action
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      with:
        # The path to the xcworkspace to build. Mutually exclusive with `project`.
        workspace: [app_name]/[app_name].xcworkspace
        # The scheme to build. Required when using a workspace.
        scheme: [scheme]
```
