### ISSUE TITLE
Issue choosing a simulator

### ISSUE THREAD

**Issue by varunchitturi** [sersoft-gmbh/xcodebuild-action#3]
getting this error when building my project

 xcodebuild: error: Unable to find a destination matching the provided destination specifier:
  		{ platform:iOS Simulator, OS:latest, name:iPhone 11 }
  
  	Ineligible destinations for the "Ghosting Connector" scheme:
  		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
  		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }

**Comment by ffried** [comment]
@varunchitturi Strange... Can you post your action definition? 
Also, are you changing the Xcode version (`xcode-select`) by any chance? If so, to what version?

**Comment by varunchitturi** [comment]
"
this is my action.yml file and i am using xcode 11.4

    runs-on: macos-latest
    strategy:
      matrix:
        destination:
          - platform=iOS Simulator,OS=13.4,name=iPhone 11
        action: [ build ]
        use-xcpretty: [ true, false ]
        include:
          - destination: platform=iOS Simulator,OS=13.4,name=iPhone 11
            action: build
            skip-testing:  true
            use-xcpretty: true

    steps:
      - run: sudo xcode-select -s /Applications/Xcode_11.4.app/Contents/Developer
      - uses: actions/checkout@v2
      - uses: sersoft-gmbh/xcodebuild-action@master
        with:
          workspace:  Ghosting Connector.xcworkspace
          scheme: Ghosting Connector
          destination: ${{matrix.destination}}
          skip-testing: ${{matrix.skip-testing}}
          action: ${{matrix.action}}
          use-xcpretty: ${{matrix.use-xcpretty}}"

**Comment by ffried** [comment]
@varunchitturi Can you verify that the following command works for you on your local machine?
`xcodebuild build -workspace "Ghosting Connector.xcworkspace" -scheme "Ghosting Connector" -destination "iOS Simulator,OS=13.4,name=iPhone 11"`

Also, the `skip-testing` parameter is passed as `-skipTesting` to `xcodebuild`:
```
    -skip-testing                                            constrains testing by specifying tests to exclude, but including other tests
    -skip-testing:TEST-IDENTIFIER                            constrains testing by specifying tests to exclude, but including other tests
```
Passing `true` will not have any effect.

I think you could simplify your yaml to this (the matrix has not much effect in your yaml, either):
```
runs-on: macos-latest
steps:
  - run: sudo xcode-select -s /Applications/Xcode_11.4.app/Contents/Developer
  - uses: actions/checkout@v2
  - uses: sersoft-gmbh/xcodebuild-action@v1
    with:
      action: build
      workspace: Ghosting Connector.xcworkspace
      scheme: Ghosting Connector
      destination: iOS Simulator,OS=13.4,name=iPhone 11
```
