### ISSUE TITLE
How does one specfiy multiple tests to be skipped?

### ISSUE THREAD

**Issue by GrayedFox** [sersoft-gmbh/xcodebuild-action#43]
As a dev-ops engineer, I would like to be able to specify a list of tests to skip or only test.

Here is an example yml config that will fail:

```yml
name: Swift Integration Tests

on:
  pull_request:
    branches:
  push:
    branches:
      - master

jobs:
  test:
    name: Tests
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.4,name=iPhone 12 Pro Max']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Test
        uses: sersoft-gmbh/xcodebuild-action@v1
        with: 
          project: OurSDK.xcodeproj
          scheme: OurSDKTests
          destination: ${{ matrix.destination }}
          action: test
          skip-testing:
              - SDK/SDKFilterTests/testBlurFilter
              - SDK/SDKLocationTests/testRealLocation
              - SDK/SDKMiscTests/
```

This will fail due to skip-testing not expecting a sequence. This will pass:

```
...
    skip-testing: 'SDK/SDKFilterTests/testBlurFilter'
```

But now how can I define other tests to skip, given that duplicate keys with different values in YAML will simply overwrite the first key?
