### ISSUE TITLE
How to add Frameworks, Other Linker Flags and keys on ".plist" to project?

### ISSUE THREAD

**Issue by gustavottc** [sersoft-gmbh/xcodebuild-action#5]
Hello, I'm currently working on a job to export a game engine project "Godot" to iOS, the job will export (working), and test in xcode (not working). 

I've been researching a little and could do this with xcodebuild, but I'm not getting it, until I found this Action from GitHub, but I found no part to add framework in the documentation, its possible with this action?

I want to add frameworks, add linker flags and add keys on ".plist" file.

If this action can not do this, thats ok, but if possible tell me how to do this directly using the command xcodebuild, thanks

**Comment by ffried** [comment]
First of all, a lot of this sounds like you should be extending your Xcode project and schemes with what you need. The advantage would be that it's very easy to reproduce locally what the CI does, without having to put together a whole lot of parameters for a command.

Apart from that:
You can currently work around any missing parameters to `xcodebuild` by using the `build-settings` parameter of this action. We currently also use this for example [here](https://github.com/sersoft-gmbh/XMLWrangler/blob/master/.github/workflows/swift-test.yml#L88).

Please give this a shot. Do you think you could also provide me with an `xcodebuild` invocation that you use? If we find that a particular parameter to `xcodebuild` is frequently used but not yet supported by this action, we're happy to extend the action with that parameter.

**Comment by gustavottc** [comment]
@ffried , thanks for your qucikly response, this is my ```xcodebuild``` workflow command: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/blob/master/.github/workflows/export_ios_project.yml#L72

I am quite new to iOS development, this project is part of a module for Godot, the module is for AdMob iOS and Android, for iOS I need to make these settings in the XCode project:

https://developers.google.com/admob/ios/quick-start#import_the_mobile_ads_sdk

I can download the SDK, but I can't import the frameworks into the XCode project, I also don't know how to add the -ObjC Other Linker Flags and Update the app's Info.plist file to add two keys along with xcodebuild

(it needs to be done entirely by xcodebuild or something, because whenever an update arrives on the module, the project needs to be exported from the beginning and loses the settings)

Thanks

**Comment by ffried** [comment]
Thanks for the `xcodebuild` command. I think we can make this work for you.

First, we need to distinguish between the Info.plist and the Xcode project. `xcodebuild` can't update your Info.plist. `xcodebuild` itself usually does not even modify the project file. It does what it says on the tin - it _builds_ the project 😉 

What I don't understand yet, is why you need to re-create the project on every update? Even if you need to do this, I'd recommend having a look at xcconfig files. Most dependency managers (like Swift Package Manager, CocoaPods and Carthage) and many other projects use them to manage build settings outside of the Xcode project - thus not loosing them if the project has to be recreated for some reason.

Again, the Info.plist is a separate file, that should usually have even less reasons to be re-generated. Modifying the Info.plist is also something that we very likely won't ever do in this action. It's not too complicated using e.g. PlistBuddy (which comes with macOS), however. So I'd recommend doing this in a simple shell script.

Back to your command: While the points I just raised are still valid, the following snippet should do the same as your current command (you should only need to specify the `project` in the snippet):
```yml
- uses: sersoft-gmbh/xcodebuild-action@v1
  with:
    project: path/to/your/project.xcodeproj
    configuration: Debug
    action: build
    sdk: iphonesimulator14.0
    build-settings: -target AdMob -arch x86_64 -allowProvisioningUpdates OTHER_LDFLAGS="-ObjC" FRAMEWORK_SEARCH_PATHS="/Users/runner/work/Godot-AdMob-Android-iOS/Godot-AdMob-Android-iOS/AdMob/GoogleMobileAdsSdkiOS-7.68.0/GoogleMobileAds.xcframework/ios-i386_x86_64-simulator"
        OTHER_LIBTOOLFLAGS="/Users/runner/work/Godot-AdMob-Android-iOS/Godot-AdMob-Android-iOS/AdMob/GoogleMobileAdsSdkiOS-7.68.0/GoogleMobileAds.xcframework/ios-i386_x86_64-simulator"
```

**Comment by gustavottc** [comment]
Thanks, i will try right now

**Comment by ffried** [comment]
I have good news for you! 🙂 
I've just released version 1.3.0, which contains a whole bunch of new options that can be passed. This means, that you can use `build-settings` for what it was originally designed and the workaround is no longer necessary:

```yml
- uses: sersoft-gmbh/xcodebuild-action@v1
  with:
    project: path/to/your/project.xcodeproj
    configuration: Debug
    action: build
    sdk: iphonesimulator14.0
    arch: x86_64
    target: AdMob
    allow-provisioning-updates: true
    build-settings: OTHER_LDFLAGS="-ObjC" FRAMEWORK_SEARCH_PATHS="/Users/runner/work/Godot-AdMob-Android-iOS/Godot-AdMob-Android-iOS/AdMob/GoogleMobileAdsSdkiOS-7.68.0/GoogleMobileAds.xcframework/ios-i386_x86_64-simulator" OTHER_LIBTOOLFLAGS="/Users/runner/work/Godot-AdMob-Android-iOS/Godot-AdMob-Android-iOS/AdMob/GoogleMobileAdsSdkiOS-7.68.0/GoogleMobileAds.xcframework/ios-i386_x86_64-simulator"
```

Another hint: be careful with absolute paths. GitHub might change the path where actions are executed and your action will break. It's better to use relative paths, or (for the build settings) [project variables](https://help.apple.com/xcode/mac/8.0/#/itcaec37c2a6)
The one you might need is actually `PROJECT_DIR` (which is not documented unfortunately). Here's an [answer on stackoverflow](https://stackoverflow.com/a/6911421) which lists it though.
