### ISSUE TITLE
unable to find simulator

### ISSUE THREAD

**Issue by paulz** [sersoft-gmbh/xcodebuild-action#66]
Thank you for the great action!

Would you please help how to specify iOS simulator correctly?

https://github.com/Lucra-Sports/ExploratoryTests/blob/11be4b4b6618b53518a8b27218f6cc4897b0075f/.github/workflows/ios-simulator.yml#L16-L29
```
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'
      - run: xcrun xctrace list devices
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: Experiments.xcodeproj
          scheme: Experiments
          sdk: iphonesimulator
          result-bundle-path: test-results/all-tests
          destination: 'platform=iOS Simulator,name=iPhone 12'
```

getting:
```
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
[19](https://github.com/Lucra-Sports/ExploratoryTests/runs/6036429190?check_suite_focus=true#step:5:19)
  		{ platform:iOS Simulator, OS:latest, name:iPhone 12 }
[20](https://github.com/Lucra-Sports/ExploratoryTests/runs/6036429190?check_suite_focus=true#step:5:20)
  
[21](https://github.com/Lucra-Sports/ExploratoryTests/runs/6036429190?check_suite_focus=true#step:5:21)
  	Ineligible destinations for the "Experiments" scheme:
[22](https://github.com/Lucra-Sports/ExploratoryTests/runs/6036429190?check_suite_focus=true#step:5:22)
  		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
[23](https://github.com/Lucra-Sports/ExploratoryTests/runs/6036429190?check_suite_focus=true#step:5:23)
  		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
[24](https://github.com/Lucra-Sports/ExploratoryTests/runs/6036429190?check_suite_focus=true#step:5:24)
  Error: Xcodebuild action failed (70)!
```

https://github.com/Lucra-Sports/ExploratoryTests/runs/6036429190?check_suite_focus=true
