### ISSUE TITLE
Getting clang error

### ISSUE THREAD

**Issue by Israphel** [sersoft-gmbh/xcodebuild-action#7]
I have the following build line:

`xcodebuild -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -project 'Split.xcodeproj' -scheme 'Split' -destination 'platform=iOS Simulator,OS=13.2.2,name=iPhone 11 Pro Max' -derivedDataPath "${GITHUB_WORKSPACE}" build | xcpretty`

Which I converted to:

```
    - name: Build with action
      uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        project: Split.xcodeproj
        scheme: Split
        destination: 'platform=iOS Simulator,OS=13.2.2,name=iPhone 11 Pro Max'
        sdk: 'iphonesimulator'
        build-settings: ONLY_ACTIVE_ARCH=NO
        derived-data-path: "${GITHUB_WORKSPACE}"
        use-xcpretty: true
        action: build
```

The single line version works ok, but for the action one I'm getting some clang errors:

```
  ▸ Compiling Split_vers.c
  
  ❌  clang: error: no such file or directory: '/Users/runner/work/ios-client/ios-client//Users/runner/work/ios-client/ios-client/ModuleCache.noindex/Session.modulevalidation'
  
  
  ▸ Compiling JFRandom.m
  
  ❌  clang: error: no such file or directory: '/Users/runner/work/ios-client/ios-client//Users/runner/work/ios-client/ios-client/ModuleCache.noindex/Session.modulevalidation'
  
  
  ▸ Compiling JFBCrypt.m
  
  ❌  clang: error: no such file or directory: '/Users/runner/work/ios-client/ios-client//Users/runner/work/ios-client/ios-client/ModuleCache.noindex/Session.modulevalidation'
  
  
  ▸ Compiling Split_vers.c
  ** BUILD FAILED **
  
  
  The following build commands failed:
  	CompileC /Users/runner/work/ios-client/ios-client/Users/runner/work/ios-client/ios-client/Build/Intermediates.noindex/Split.build/Debug-iphonesimulator/Split.build/Objects-normal/x86_64/Split_vers.o /Users/runner/work/ios-client/ios-client/Users/runner/work/ios-client/ios-client/Build/Intermediates.noindex/Split.build/Debug-iphonesimulator/Split.build/DerivedSources/Split_vers.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
  	CompileC /Users/runner/work/ios-client/ios-client/Users/runner/work/ios-client/ios-client/Build/Intermediates.noindex/Split.build/Debug-iphonesimulator/Split.build/Objects-normal/x86_64/JFRandom.o /Users/runner/work/ios-client/ios-client/Split/Common/Utils/JFBCrypt/JFRandom.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
  	CompileC /Users/runner/work/ios-client/ios-client/Users/runner/work/ios-client/ios-client/Build/Intermediates.noindex/Split.build/Debug-iphonesimulator/Split.build/Objects-normal/x86_64/JFBCrypt.o /Users/runner/work/ios-client/ios-client/Split/Common/Utils/JFBCrypt/JFBCrypt.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
  (3 failures)
  Error: Xcodebuild action failed (65)!
```

any idea? are my parameters wrong?

I have an initial step for selecting xcode:

```
    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 11.2
```
