### ISSUE TITLE
macOS test fails to CodeSign the app

### ISSUE THREAD

**Issue by paulz** [sersoft-gmbh/xcodebuild-action#8]
running Mac OS application tests fails to code sign. When we run xcodebuild as a shell command it succeeds.

```
  ▸ Signing ~/DerivedData/App-.../Build/Products/Debug/App.app/Contents/Frameworks/MyFramework.framework
34
  ▸ Running script '[CP] Embed Pods Frameworks'
35
  ** TEST FAILED **
36
  
37
  
38
  The following build commands failed:
39
  	CodeSign ../DerivedData/App-.../Build/Products/Debug/App.app
40
  (1 failure)
41
  Error: Xcodebuild action failed (65)!
```

**Comment by paulz** [comment]
fixed by `clean`, it would be nice if action supported rerun with clean on failure

**Comment by ffried** [comment]
First of all good to hear that you were able to fix it!

You can specify multiple actions to perform:

```yml
uses: sersoft-gmbh/xcodebuild-action@v1
with:
  project: MyApp.xcodeproj
  scheme: MyApp
  destination: platform=macOS
  action: clean test
```

This example would be equivalent to the following execution of `xcodebuild`:
`xcodebuild -project MyApp.xcodeproj -scheme MyApp -destination 'platform=macOS' clean test`

Does that help?

**Comment by paulz** [comment]
thank you, good to know multiple actions are supported.

We are taking advantage of derived data on self hosted runner by not doing clean build.

It would nice to be able to rerun `clean test` action only when `test` has failed. This way we can have fast feedback. Meantime clean test would confirm that when failures happened they are not related to unclean state.

**Comment by ffried** [comment]
This should be doable with GitHub Actions out of the box:

```yml
- uses: sersoft-gmbh/xcodebuild-action@v1
  with:
    project: MyApp.xcodeproj
    scheme: MyApp
    destination: platform=macOS
    action: test
- uses: sersoft-gmbh/xcodebuild-action@v1
  if: failure()
  with:
    project: MyApp.xcodeproj
    scheme: MyApp
    destination: platform=macOS
    action: clean test
```

The second action (which includes the `clean` command) only runs if the first one failed.
