### ISSUE TITLE
Using iOS platform (it does work, not only macOS) and issues with specifying spm-package

### ISSUE THREAD

**Issue by JeneaVranceanu** [sersoft-gmbh/xcodebuild-action#94]
In README.md it's stated that only macOS destination will work but that appears to be false.
I've specified destination as following and it did work fine:
```yml
destination: platform=iOS Simulator,name=iPhone 13
```

I'm testing an SPM package and one other weird thing is that I had to set spm-package as `.` in order for the action to work:
```yml
spm-package: .
``` 

Here are all jobs that run during CI:
```yml
jobs:
  spm:
    name: Swift Package Manager
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v2
      - name: Resolve dependencies
        run: swift package resolve
      - uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          spm-package: .
          scheme: UniversalProfile
          destination: platform=iOS Simulator,name=iPhone 13
          action: test
```

P.S. Thanks for this GitHub Action!
